import { DOCUMENT, NgTemplateOutlet, isPlatformBrowser } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  PLATFORM_ID,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';
import { toObservable, toSignal } from '@angular/core/rxjs-interop';
import { RouterLink } from '@angular/router';
import { debounceTime } from 'rxjs/operators';
import { RhombusButtonComponent, RhombusSliderComponent } from '@rhombuskit/core';
import {
  RhombusThemeService,
  type RegisteredTheme,
  type ThemePreference,
} from '@rhombuskit/theme-engine';
import {
  generateTheme,
  serializeThemeCss,
  toAugmentation,
  toRegisteredThemes,
  type GeneratedTheme,
  type ThemeSeed,
} from '@rhombuskit/theme-builder';

/** The shipped violet/slate seeds — passing these reproduces the built-in packs. */
const CANON_ACCENT = '#7c3aed';
const CANON_NEUTRAL = '#64748b';
/** Fixed name for the LOCAL preview subtree — never the app-wide `html[data-theme]`. */
const PREVIEW_NAME = 'tb-preview';
/** Single id-guarded <style> that carries the preview subtree rules. */
const PREVIEW_STYLE_ID = 'rk-theme-builder-preview';
/**
 * A SEPARATE name + <style> for "Apply to whole app". Kept distinct from the live
 * preview so a later remount of this page (which rewrites the preview <style> from
 * the default seed) can't silently revert an already-applied theme — the applied
 * CSS is a snapshot this page never overwrites except on an explicit re-apply.
 */
const APPLIED_NAME = 'tb-applied';
const APPLIED_STYLE_ID = 'rk-theme-builder-applied';
const HEX_RE = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/;

interface GenResult {
  theme: GeneratedTheme | null;
  error: string | null;
}

/** Never throw into the template: a pathological neutral can exhaust the nudge. */
function safeGenerate(seed: ThemeSeed): GenResult {
  try {
    return { theme: generateTheme(seed), error: null };
  } catch (e) {
    return { theme: null, error: e instanceof Error ? e.message : String(e) };
  }
}

/** One `[data-theme]{…}` block over every token in the record. */
function block(name: string, values: Record<string, string>): string {
  const body = Object.entries(values)
    .map(([k, v]) => `${k}: ${v};`)
    .join(' ');
  return `[data-theme="${name}"] { ${body} }`;
}

/**
 * A light + dark `[data-theme]` pair under one base name (`X` / `X-dark`). Used
 * both for the local preview subtrees and for the "Apply to whole app" snapshot.
 * Injected into <head>, it themes by cascade WITHOUT writing `html[data-theme]`.
 */
function pairCss(baseName: string, theme: GeneratedTheme): string {
  return `${block(baseName, theme.light)}\n${block(`${baseName}-dark`, theme.dark)}\n`;
}

/** `toRegisteredThemes()` rendered as the `provideRhombusThemes(...)` call from docs/theming.md. */
function registrationSnippet(theme: GeneratedTheme): string {
  const lines = toRegisteredThemes(theme)
    .map(
      (t) =>
        `  { name: '${t.name}', label: '${t.label}', mode: '${t.mode}', palette: '${t.palette}' },`,
    )
    .join('\n');
  return [
    `import { provideRhombusThemes } from '@rhombuskit/theme-engine';`,
    ``,
    `// Add to your application providers:`,
    `provideRhombusThemes(`,
    lines,
    `);`,
  ].join('\n');
}

/** A lowerCamel identifier for the exported const names in the .ts module. */
function camelName(name: string): string {
  const pascal = name.replace(/[^a-zA-Z0-9]+(.)?/g, (_, c: string | undefined) =>
    c ? c.toUpperCase() : '',
  );
  return pascal.charAt(0).toLowerCase() + pascal.slice(1) || 'theme';
}

/** The third output format: a standalone TS theme-pack module (light + dark records). */
function tsModule(theme: GeneratedTheme): string {
  const id = camelName(theme.name);
  return [
    `// ${theme.name} — generated by the RhombusKit theme builder.`,
    `// A token theme-pack over the 60-name CONTRACT (light + dark). Pair with the`,
    `// registration snippet and the [data-theme] CSS to apply it.`,
    `import type { SemanticTokenName } from '@rhombuskit/tokens';`,
    ``,
    `export const ${id}Light: Record<SemanticTokenName, string> = ${JSON.stringify(theme.light, null, 2)};`,
    ``,
    `export const ${id}Dark: Record<SemanticTokenName, string> = ${JSON.stringify(theme.dark, null, 2)};`,
    ``,
  ].join('\n');
}

/**
 * `/theme-builder` — the interactive front-end for `@rhombuskit/theme-builder`.
 * Pick one or two seed colours, watch a live light + dark preview, and copy or
 * download the AA-validated theme in any of the three sanctioned forms.
 *
 * Preview is LOCAL by construction (spec §7/C6): the generated packs are injected
 * as `[data-theme="tb-preview"]` / `…-dark` rules and rendered into two subtree
 * `<div>`s, so the cascade themes them without touching the global `html[data-theme]`
 * — which stays owned solely by `RhombusThemeService`. That keeps the contrast e2e's
 * global-theme assertion intact while still letting axe scan the generated theme.
 *
 * The export blocks are plain reactive `<pre>`s rather than `<rhombus-code-block>`:
 * the code-block paints its `code` once in `ngAfterViewInit`, so a live-updating
 * export would go stale on the first seed change.
 */
@Component({
  selector: 'app-theme-builder-page',
  standalone: true,
  imports: [
    RouterLink,
    NgTemplateOutlet,
    RhombusButtonComponent,
    RhombusSliderComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styleUrl: './theme-builder-page.component.scss',
  template: `
    <div class="showcase-page theme-builder">
      <header class="showcase-page__header">
        <h1>Theme builder</h1>
        <p>
          A visual front-end for
          <code>&#64;rhombuskit/theme-builder</code>. Give it a brand accent (and,
          optionally, a neutral) and it derives a complete light + dark theme over
          all 60 contract tokens — re-validated for WCAG&nbsp;AA contrast, so it
          either hands you an AA-clean theme or tells you why it can't. Everything
          runs in your browser; nothing is uploaded.
        </p>
      </header>

      <section class="showcase-section">
        <h2>Seeds</h2>
        <div class="tb-controls">
          <div class="tb-field">
            <label for="tb-accent">Accent</label>
            <div class="tb-field__row">
              <input
                id="tb-accent"
                #accentEl
                type="color"
                class="tb-swatch"
                [value]="accent()"
                (input)="setAccentHex(accentEl.value)"
              />
              <code class="tb-field__hex">{{ accent() }}</code>
            </div>
            <p class="tb-field__hint">The one colour every brand owns.</p>
          </div>

          <div class="tb-field">
            <label for="tb-neutral">Neutral</label>
            <div class="tb-field__row">
              <input
                id="tb-neutral"
                #neutralEl
                type="color"
                class="tb-swatch"
                [value]="neutral()"
                (input)="setNeutralHex(neutralEl.value)"
              />
              <code class="tb-field__hex">{{ neutral() }}</code>
            </div>
            <p class="tb-field__hint">Warms or cools the greys. Optional.</p>
          </div>

          <div class="tb-field">
            <label for="tb-name">Theme name</label>
            <div class="tb-field__row">
              <input
                id="tb-name"
                type="text"
                class="tb-text"
                autocomplete="off"
                spellcheck="false"
                [placeholder]="theme()?.name ?? 'auto'"
                (input)="setName(nameEl.value)"
                #nameEl
              />
            </div>
            <p class="tb-field__hint">Defaults to the accent's hue name.</p>
          </div>

          <div class="tb-field tb-field--wide">
            <span class="tb-field__label">Vividness — {{ vividnessLabel(vividness()) }}</span>
            <rhombus-slider
              ariaLabel="Vividness"
              [min]="0.5"
              [max]="1.5"
              [step]="0.1"
              [value]="vividness()"
              discrete
              [displayWith]="vividnessLabel"
              (valueChange)="setVividness($event)"
            />
            <p class="tb-field__hint">
              Scales generated ramp chroma. No effect on contrast.
            </p>
          </div>
        </div>

        @if (error(); as message) {
          <p class="tb-status tb-status--error" role="status">
            <strong>Can't build an AA-clean theme from this neutral.</strong>
            {{ message }} Pick a neutral closer to grey.
          </p>
        } @else {
          <p class="tb-status tb-status--pass" role="status">
            <strong>AA verified.</strong> All 24 text pairs (4.5:1) and 4 badge
            pairs (3:1) clear in both light and dark.
          </p>
        }

        @if (warnings().length) {
          <ul class="tb-warnings" aria-label="Fidelity warnings">
            @for (w of warnings(); track w) {
              <li>{{ w }}</li>
            }
          </ul>
        }
      </section>

      <section class="showcase-section">
        <h2>Live preview</h2>
        <p>
          Each panel is a local <code>data-theme</code> subtree — the generated
          theme cascades into it without changing the app's own theme. Toggle the
          site theme in the header; these panels don't move.
        </p>
        <div class="tb-previews">
          <div class="tb-preview" data-theme="tb-preview">
            <span class="tb-preview__mode">Light</span>
            <ng-container [ngTemplateOutlet]="previewBody" />
          </div>
          <div class="tb-preview" data-theme="tb-preview-dark">
            <span class="tb-preview__mode">Dark</span>
            <ng-container [ngTemplateOutlet]="previewBody" />
          </div>
        </div>
      </section>

      <section class="showcase-section">
        <h2>Export</h2>
        <p>
          The two-step path from <a routerLink="/theming">the theming guide</a>:
          ship the CSS, then register the names. All three forms come from one
          generate call.
        </p>

        <div class="tb-export">
          <div class="tb-export__head">
            <span class="tb-export__label">1 · Theme CSS — the <code>[data-theme]</code> blocks</span>
            <button type="button" class="tb-copy" (click)="copy(cssExport(), 'css')">
              {{ copiedKey() === 'css' ? 'Copied' : 'Copy' }}
            </button>
          </div>
          <pre class="tb-export__pre tb-scroll"><code>{{ cssExport() }}</code></pre>
        </div>

        <div class="tb-export">
          <div class="tb-export__head">
            <span class="tb-export__label">2 · Register the names</span>
            <button type="button" class="tb-copy" (click)="copy(registrationExport(), 'reg')">
              {{ copiedKey() === 'reg' ? 'Copied' : 'Copy' }}
            </button>
          </div>
          <pre class="tb-export__pre tb-scroll"><code>{{ registrationExport() }}</code></pre>
        </div>

        <div class="tb-export">
          <div class="tb-export__head">
            <span class="tb-export__label">3 · Type augmentation (so <code>setTheme()</code> checks)</span>
            <button type="button" class="tb-copy" (click)="copy(augmentationExport(), 'aug')">
              {{ copiedKey() === 'aug' ? 'Copied' : 'Copy' }}
            </button>
          </div>
          <pre class="tb-export__pre tb-scroll"><code>{{ augmentationExport() }}</code></pre>
        </div>

        <div class="tb-actions">
          <rhombus-button variant="secondary" (click)="downloadCss()">
            Download .css
          </rhombus-button>
          <rhombus-button variant="secondary" (click)="downloadTs()">
            Download .ts module
          </rhombus-button>
          <rhombus-button variant="primary" (click)="applyToApp()">
            Apply to whole app
          </rhombus-button>
        </div>
        @if (applied()) {
          <p class="tb-applied" role="status">
            Applied for this session. Switch back with the theme menu in the header
            — it isn't persisted across reload.
          </p>
        }
      </section>
    </div>

    <ng-template #previewBody>
      <div class="tb-preview__card">
        <h3 class="tb-preview__title">Aa — heading</h3>
        <p class="tb-preview__secondary">Secondary body text on the base background.</p>
        <p class="tb-preview__muted">Muted helper text sits a step quieter.</p>
        <p><a class="tb-preview__link" href="#" (click)="$event.preventDefault()">An accent link</a></p>
        <div class="tb-preview__surface">
          <span>Text on a raised surface</span>
          <span class="tb-preview__accent">accent</span>
        </div>
        <div class="tb-preview__row">
          <span class="tb-preview__btn">Primary</span>
          <span class="tb-preview__chip">Published</span>
        </div>
      </div>
    </ng-template>
  `,
})
export default class ThemeBuilderPageComponent {
  private readonly doc = inject(DOCUMENT);
  private readonly platformId = inject(PLATFORM_ID);
  private readonly themeService = inject(RhombusThemeService);

  // Raw controls — updated immediately so the pickers feel live.
  protected readonly accent = signal(CANON_ACCENT);
  protected readonly neutral = signal(CANON_NEUTRAL);
  protected readonly vividness = signal(1);
  protected readonly themeName = signal('');
  protected readonly copiedKey = signal<string | null>(null);
  protected readonly applied = signal(false);

  /** The seed assembled from the controls — recomputes synchronously on any change. */
  private readonly seed = computed<ThemeSeed>(() => {
    const s: ThemeSeed = {
      accent: this.accent(),
      neutral: this.neutral(),
      vividness: this.vividness(),
    };
    const name = this.themeName().trim();
    if (name) s.name = name;
    return s;
  });

  /**
   * The seed, debounced — a drag on a colour picker or the slider fires a burst
   * of changes; regenerate only once it settles. The initial value is the default
   * seed, so first render (and SSR) is synchronous with no wait.
   */
  private readonly debouncedSeed = toSignal(
    toObservable(this.seed).pipe(debounceTime(150)),
    { initialValue: this.seed() },
  );

  protected readonly generated = computed<GenResult>(() =>
    safeGenerate(this.debouncedSeed()),
  );

  protected readonly theme = computed(() => this.generated().theme);
  protected readonly error = computed(() => this.generated().error);
  protected readonly warnings = computed(() => this.theme()?.report.warnings ?? []);
  protected readonly cssExport = computed(() => {
    const t = this.theme();
    return t ? serializeThemeCss(t) : '';
  });
  protected readonly registrationExport = computed(() => {
    const t = this.theme();
    return t ? registrationSnippet(t) : '';
  });
  protected readonly augmentationExport = computed(() => {
    const t = this.theme();
    return t ? toAugmentation(t) : '';
  });

  private readonly styleEl: HTMLStyleElement;

  protected readonly vividnessLabel = (v: number): string => `${v.toFixed(1)}×`;

  constructor() {
    // Find or create the single id-guarded preview <style>. Seeding it here (not
    // only in the effect) runs on the server too, so the prerendered HTML already
    // carries the preview CSS and there's no unthemed first paint.
    this.styleEl = this.ensureStyle(PREVIEW_STYLE_ID);
    this.writePreview(this.generated().theme);

    // Keep the subtree CSS in sync with the debounced seed. Browser-only: the
    // debounced signal never advances past its initial value during SSR.
    if (isPlatformBrowser(this.platformId)) {
      effect(() => this.writePreview(this.generated().theme));
    }
  }

  /** Find-or-create an id-guarded <style> in <head> (SSR-safe via the injected DOCUMENT). */
  private ensureStyle(id: string): HTMLStyleElement {
    const existing = this.doc.getElementById(id) as HTMLStyleElement | null;
    if (existing) return existing;
    const el = this.doc.createElement('style');
    el.id = id;
    this.doc.head.appendChild(el);
    return el;
  }

  private writePreview(theme: GeneratedTheme | null): void {
    // On a throw (pathological neutral) keep the last good CSS so the preview
    // doesn't blank out mid-edit; the status banner explains the failure.
    if (theme) this.styleEl.textContent = pairCss(PREVIEW_NAME, theme);
  }

  protected setAccentHex(raw: string): void {
    const v = raw.trim();
    if (HEX_RE.test(v)) this.accent.set(v);
  }

  protected setNeutralHex(raw: string): void {
    const v = raw.trim();
    if (HEX_RE.test(v)) this.neutral.set(v);
  }

  protected setName(raw: string): void {
    this.themeName.set(raw);
  }

  protected setVividness(value: number | { start: number; end: number }): void {
    if (typeof value === 'number') this.vividness.set(value);
  }

  protected copy(text: string, key: string): void {
    if (!isPlatformBrowser(this.platformId)) return;
    if (!navigator.clipboard) return;
    navigator.clipboard.writeText(text).then(
      () => {
        this.copiedKey.set(key);
        setTimeout(() => {
          if (this.copiedKey() === key) this.copiedKey.set(null);
        }, 1500);
      },
      // Clipboard writes reject in real conditions (not focused, permission
      // denied). Swallow it — the "Copied" label just won't appear.
      () => undefined,
    );
  }

  protected downloadCss(): void {
    const t = this.theme();
    if (t) this.download(`${t.name}.theme.css`, this.cssExport(), 'text/css');
  }

  protected downloadTs(): void {
    const t = this.theme();
    if (t) this.download(`${t.name}.theme.ts`, tsModule(t), 'text/plain');
  }

  private download(filename: string, content: string, mime: string): void {
    if (!isPlatformBrowser(this.platformId)) return;
    const url = URL.createObjectURL(new Blob([content], { type: mime }));
    const a = this.doc.createElement('a');
    a.href = url;
    a.download = filename;
    this.doc.body.appendChild(a);
    a.click();
    a.remove();
    // Defer the revoke: revoking synchronously after click() can cancel the
    // download before the browser has read the blob.
    setTimeout(() => URL.revokeObjectURL(url), 0);
  }

  /**
   * Try the theme on the whole app for the session. Writes a SNAPSHOT of the
   * current theme to the dedicated `tb-applied` <style> (separate from the live
   * preview, so revisiting this page can't revert it), registers the name, then
   * switches through the service — the sole writer of `html[data-theme]`. Not
   * persisted across reload (registerThemes is session-only, by design).
   */
  protected applyToApp(): void {
    const t = this.theme();
    if (!t) return;
    this.ensureStyle(APPLIED_STYLE_ID).textContent = pairCss(APPLIED_NAME, t);
    // The applied names aren't in the compile-time ThemeRegistry (they're fixed
    // runtime strings), so cast through `unknown` — the same escape the data-driven
    // community themes need. registerThemes is session-only, so nothing persists.
    this.themeService.registerThemes([
      { name: APPLIED_NAME, label: t.label, mode: 'light', palette: APPLIED_NAME },
      {
        name: `${APPLIED_NAME}-dark`,
        label: t.label,
        mode: 'dark',
        palette: APPLIED_NAME,
      },
    ] as unknown as RegisteredTheme[]);
    this.themeService.setTheme(APPLIED_NAME as unknown as ThemePreference);
    this.applied.set(true);
  }
}
