# Sponsoring RhombusKit is a longevity signal, not a paywall — every feature
# and fix stays free and MIT-licensed. The button below activates once GitHub
# Sponsors enrollment is complete for this account.
github: [doug-williamson]
